import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { PropsWithChildren } from 'react'

import './globals.css'
import { Footer } from '@/components/layout/footer'
import { Header } from '@/components/layout/header'

const montserrat = Montserrat({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin', 'latin-ext']
})

export const metadata: Metadata = {
  title: 'Bachu Krasyvo',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.svg',
    shortcut: '/favicon.svg',
    apple: '/favicon.svg'
  }
}

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang='uk'>
      <body className={`${montserrat.className} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout
