import { Footer } from '@/components/layout/footer'
import { Header } from '@/components/layout/header'
import { DotPattern } from '@/components/ui/dot-pattern'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { PropsWithChildren } from 'react'
import './globals.css'

const poppins = Poppins({
    variable: '--font-poppins-sans',
    weight: ['400', '500', '600', '700'],
    subsets: ['latin', 'latin-ext'],
})

export const metadata: Metadata = {
    title: 'Bachu Krasyvo',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.svg',
        shortcut: '/favicon.svg',
        apple: '/favicon.svg',
    },
}

const RootLayout = ({ children }: PropsWithChildren) => {
    return (
        <html lang="en">
            <body
                className={cn(
                    'antialiased flex flex-col justify-between min-h-screen',
                    poppins.className
                )}>
                <Header />
                <main className="flex-1 ">{children}</main>
                <Footer />
                <Toaster
                    richColors
                    duration={6000}
                />
                <DotPattern className="opacity-50 fixed inset-0 z-[1]" />
            </body>
        </html>
    )
}

export default RootLayout
